import type { Album } from '../types'

export const MOCK_ALBUMS: Album[] = [
    {
        id: 'mock-1',
        title: 'Amara & Kaveh',
        slug: 'amara-kaveh',
        category: 'Wedding',
        couple_names: 'Amara & Kaveh',
        event_date: '2024-03-15',
        location: 'Kandy, Sri Lanka',
        description: 'A timeless ceremony amidst the hills of Kandy.',
        cover_image_url: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=80',
        is_published: true,
        sort_order: 1,
        created_at: '2024-03-15T00:00:00Z',
    },
    {
        id: 'mock-2',
        title: 'Nadia & Ruwan',
        slug: 'nadia-ruwan',
        category: 'Wedding',
        couple_names: 'Nadia & Ruwan',
        event_date: '2024-05-20',
        location: 'Galle, Sri Lanka',
        description: 'Sunset vows by the colonial fort walls.',
        cover_image_url: 'https://images.unsplash.com/photo-1537633552985-df8429e8048b?w=800&q=80',
        is_published: true,
        sort_order: 2,
        created_at: '2024-05-20T00:00:00Z',
    },
    {
        id: 'mock-3',
        title: 'Ishara & Dev',
        slug: 'ishara-dev',
        category: 'Pre-Wedding',
        couple_names: 'Ishara & Dev',
        event_date: '2024-07-10',
        location: 'Sigiriya, Sri Lanka',
        description: 'Pre-wedding magic at the ancient rock fortress.',
        cover_image_url: 'https://images.unsplash.com/photo-1460978812857-470ed1c77af0?w=800&q=80',
        is_published: true,
        sort_order: 3,
        created_at: '2024-07-10T00:00:00Z',
    },
    {
        id: 'mock-4',
        title: 'Priya & Mihail',
        slug: 'priya-mihail',
        category: 'Wedding',
        couple_names: 'Priya & Mihail',
        event_date: '2024-09-08',
        location: 'Colombo, Sri Lanka',
        description: 'An elegant ballroom celebration in the heart of Colombo.',
        cover_image_url: 'https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?w=800&q=80',
        is_published: true,
        sort_order: 4,
        created_at: '2024-09-08T00:00:00Z',
    },
    {
        id: 'mock-5',
        title: 'Leila & Thomas',
        slug: 'leila-thomas',
        category: 'Fashion',
        couple_names: 'Leila & Thomas',
        event_date: '2024-10-14',
        location: 'Nuwara Eliya, Sri Lanka',
        description: 'Editorial fashion portraits in the tea country.',
        cover_image_url: 'https://images.unsplash.com/photo-1606216794074-735e91aa2c92?w=800&q=80',
        is_published: true,
        sort_order: 5,
        created_at: '2024-10-14T00:00:00Z',
    },
    {
        id: 'mock-6',
        title: 'Sena & Aria',
        slug: 'sena-aria',
        category: 'Artistic',
        couple_names: 'Sena & Aria',
        event_date: '2024-11-22',
        location: 'Mirissa, Sri Lanka',
        description: 'Artistic beach portraits at golden hour.',
        cover_image_url: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=800&q=80',
        is_published: true,
        sort_order: 6,
        created_at: '2024-11-22T00:00:00Z',
    },
]
